server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-lbj3hld8l000i6go.rwlb.rds.aliyuncs.com:3306/foodhelper #serviceTimezone=UTC
    username: foodhelper
    password: ali24@foodhelper