server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源类型(druid)
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库类型(mysql)
    url: jdbc:mysql://rm-cn-lbj3hld8l000i6go.rwlb.rds.aliyuncs.com:3306/sd #数据库地址
    username: sd_image_generation #账户名称
    password: sd1@aliyun #账户密码

  mvc:
    static-path-pattern: /static/**